### ISSUE TITLE
ImageMagick not installed when this is installed

### ISSUE THREAD

**Issue by cl0v3r404** [logonoff/framework-13-grub-theme#1]
When I run the installation script it says that ImageMagick is not installed, when I previously installed it from the Debian 12 repository. I don't know if it is a bug or my mistake.
![Captura de pantalla de 2024-07-18 13-27-55](https://github.com/user-attachments/assets/43234c74-b827-44db-9b5e-eea15f0c9be2)
![Captura de pantalla de 2024-07-18 13-26-53](https://github.com/user-attachments/assets/17f7c6ef-4a65-4741-9a3b-4ecf304a6083)

**Comment by logonoff** [comment]
I just made a fix, please [download the theme again](https://github.com/logonoff/bgrt-grub-theme/releases/download/2.0.1/bgrt-grub-theme.zip) and let me know if it works

**Comment by cl0v3r404** [comment]
Now it is working without any type of error.
